Repository CrashTeamR/HaloBuku, pull requests merged in 2022-10, with the labels that each got.

#5 Improve convention on project structure and TypeScript
  .env.example
  README.md
  package-lock.json
  package.json
  pages/api/hello.js
  src/data/books.json
  src/data/books.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/types/book.ts
  src/types/index.ts
  tsconfig.json
  yarn.lock
Labels: bug, documentation, enhancement

#10 Improve code quality
  README.md
  package-lock.json
  package.json
  src/components/layout.tsx
  src/libs/index.ts
  src/libs/swr.ts
  src/pages/_app.tsx
  src/pages/books/[bookId].tsx
  src/pages/index.tsx
  src/types/book.ts
Labels: bug, documentation, enhancement, design

#12 Fix errors only absolute URLs are supported
  src/pages/books/[bookId].tsx
  src/pages/index.tsx
Labels: bug

#15 11 specify the language for the website
  package-lock.json
  src/components/card.tsx
  src/components/header.tsx
  src/pages/index.tsx
  tailwind.config.js
Labels: enhancement, design

#16 New improvement
  package-lock.json
  package.json
  src/components/book-details.tsx
  src/components/card.tsx
  src/components/footer.tsx
  src/components/header.tsx
  src/components/index.ts
  src/components/layout.tsx
  src/components/login-button.tsx
  src/components/random-books.tsx
  src/components/register-button.tsx
  src/components/submit-button.tsx
  src/pages/books/[bookId].tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/register/index.tsx
  src/pages/verify/index.tsx
  yarn.lock
Labels: bug, enhancement, design

#24 Create functionality of search feature
  public/favicon.ico
  src/components/book-details.tsx
  src/components/card.tsx
  src/components/header.tsx
  src/pages/books/[bookId].tsx
  src/pages/index.tsx
  src/pages/search/index.tsx
Labels: bug, enhancement, design

#26 Fix update search field
  src/components/header.tsx
Labels: bug

#28 Update button interaction
  package-lock.json
  package.json
  src/components/header.tsx
  src/components/layout.tsx
  src/components/login-button.tsx
  src/components/register-button.tsx
  src/components/submit-button.tsx
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/register/index.tsx
  src/pages/verify/index.tsx
  yarn.lock
Labels: enhancement, design

#31 Update homepage ui and data
  next.config.js
  src/components/card.tsx
  src/components/header.tsx
  src/components/hidden-menu.jsx
  src/components/logout-button.tsx
  src/data/books.json
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/register/index.tsx
Labels: design

#33 Update the cart page
  src/components/add-cart-button.tsx
  src/components/book-details.tsx
  src/components/card-book-cart.tsx
  src/components/header.tsx
  src/components/index.ts
  src/components/register-button.tsx
  src/pages/cart/index.tsx
Labels: enhancement, design

#34 Add logout button to the display
  src/components/header.tsx
  src/data/books.json
Labels: enhancement
